config/routes.rb
Rails.application.routes.draw do

  namespace :site do
    get 'depoimentos' => 'depoimentos#index'
    get 'home' => "home#index"
    get 'sobre' => "sobre#index"
    get 'contato' => "contato#index"
    get 'galeria' => "galeria#index"
    get 'servicos' => "servicos#index"
    get 'servicos/:id' => "servicos#show"
    get 'clientes' => "clientes#index"
    resources 'contato', only: [:create, :new]
  end

  get 'admin' => 'backoffice/requests#index'

  namespace :backoffice do
    get 'dashboard/index' => 'request#index'
    resources :categories, except: [:show]
    resources :services, except: [:show]
    resources :clients, except: [:show]
    resources :requests, only: [:index, :show, :destroy, :update]
    resources :testimonials, except: [:show]
    resources :menus
    get 'menus/new/:id' => 'menus#new', as: :new_backoffice_menu_service
  end

  root 'site/home#index'
  
  devise_for :admins, :skips => [:registrations]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :service
	validates :description, presence: true
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController

	def index
		@categories = Category.all
	end

end

app/controllers/backoffice/clients_controller.rb
class Backoffice::ClientsController < BackofficeController
  before_action :set_client, only: [:edit, :destroy, :update]  

  def index
  	@clients = Client.all
  end

  def new  
  	@client = Client.new
  end

  def create
  	@client = Client.new(params_client)
  	if @client.save
  		redirect_to backoffice_clients_path, notice: "Cliente #{@client.name} cadastrado com sucesso"
  	else
  		render :new
  	end	
  end

  def destroy
  
  if @client.destroy
      redirect_to backoffice_clients_path, notice: "Cliente removido"
    else
      render :index
    end
  end

  def edit
  end

  def update
    if (@client.update(params_client))
      redirect_to backoffice_clients_path, notice: "Cliente #{@client.name} atualizado com sucesso"
    else
      render :edit
    end
  end

  private 

  def params_client
  	params.require(:client).permit(:name, :description, :website, :picture)  	
  end
  
  def set_client
    @client = Client.find(params[:id])
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/menus_controller.rb
class Backoffice::MenusController < BackofficeController
    before_action :set_menu, only: [:edit, :destroy, :update, :show]
    before_action :set_services, only: [:new, :create, :edit, :update]

  def index
  	@menus = Menu.all
  end

  def show
    
  end

  def new    
  	@menu = Menu.new    
    @menu.service_id = params[:id]    
  end

  def create
  	@menu = Menu.new(params_menu)
  	if @menu.save
  		redirect_to backoffice_menus_path, notice: "Cardápio cadastrado com sucesso"
  	else
  		render :new
  	end	
  end

  def destroy
  
  if @menu.destroy
      redirect_to backoffice_menus_path, notice: "Cardápio removido"
    else
      render :index
    end
  end

  def edit
  end

  def update
    if (@menu.update(params_menu))
      redirect_to backoffice_menus_path, notice: "Cardápio atualizado com sucesso"
    else
      render :edit
    end
  end

  private 

  def set_services
    @services = Service.all.order(:title)    
  end

  def params_menu
  	params.require(:menu).permit(:title, :description, :service_id, drinks_attributes: [:id, :name, :_destroy], foods_attributes: [:id, :name, :_destroy])  	
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end
end

app/controllers/backoffice/requests_controller.rb
class Backoffice::RequestsController < BackofficeController
	before_action :set_request, only: [:show, :destroy]
  
  def index
  	@requests = Request.all.order(created_at: :desc).page(params[:page]).per(20)
    @received_emails = Request.count
    @clients_registered = Client.count
    @services_registered = Service.count
    @testimonials_registered = Testimonial.count
  end

  def destroy  
  	if @request.destroy
      redirect_to backoffice_requests_path, notice: "E-mail removido"
    else
      render :index
    end
  end

  def show
  end

  private

  def set_request
  	@request = Request.find(params[:id])
  end

end

app/controllers/backoffice/services_controller.rb
class Backoffice::ServicesController < BackofficeController
  before_action :set_service, only: [:edit, :destroy, :update]
  before_action :set_categories, only: [:new, :create, :edit, :update]

  def index
  	@services = Service.all
  end

  def new  
  	@service = Service.new
  end

  def create
  	@service = Service.new(params_service)
  	if @service.save
  		redirect_to backoffice_services_path, notice: "Serviço #{@service.title} cadastrado com sucesso"
  	else
  		render :new
  	end	
  end

  def destroy
  
  if @service.destroy
      redirect_to backoffice_services_path, notice: "Serviço removido"
    else
      render :index
    end
  end

  def edit
  end

  def update
    if (@service.update(params_service))
      redirect_to backoffice_services_path, notice: "Serviço #{@service.title} atualizado com sucesso"
    else
      render :edit
    end
  end

  private 

  def params_service
  	params.require(:service).permit(:title, :description, :category_id, :slogan, :picture)  	
  end

  def set_categories
      @categories = Category.all.order(:description)
  end

  def set_service
    @service = Service.find(params[:id])
  end

end

app/controllers/backoffice/testimonials_controller.rb
class Backoffice::TestimonialsController < BackofficeController
  before_action :set_testimonial, only: [:edit, :destroy, :update]

  def index
  	@testimonials = Testimonial.all.order(created_at: :desc)
  end

  def new  
  	@testimonial = Testimonial.new
  end

  def create
  	@testimonial = Testimonial.new(params_testimonial)
  	if @testimonial.save
  		redirect_to backoffice_testimonials_path, notice: "Depoimento cadastrado com sucesso"
  	else
  		render :new
  	end	
  end

  def destroy
  
  if @testimonial.destroy
      redirect_to backoffice_testimonials_path, notice: "Depoimento removido"
    else
      render :index
    end
  end

  def edit
  end

  def update
    if (@testimonial.update(params_testimonial))
      redirect_to backoffice_testimonials_path, notice: "Depoimento atualizado com sucesso"
    else
      render :edit
    end
  end

  private 

  def params_testimonial
  	params.require(:testimonial).permit(:message, :name, :company)  	
  end

  def set_testimonial
    @testimonial = Testimonial.find(params[:id])
  end

end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

	layout "backoffice"

	before_action :authenticate_admin!



end

app/helpers/backoffice/clients_helper.rb
module Backoffice::ClientsHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/menus_helper.rb
module Backoffice::MenusHelper
end

app/helpers/backoffice/requests_helper.rb
module Backoffice::RequestsHelper

end

app/helpers/backoffice/services_helper.rb
module Backoffice::ServicesHelper
end

app/helpers/backoffice/testimonials_helper.rb
module Backoffice::TestimonialsHelper
end

app/views/backoffice/categories/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Categorias</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-8">   
                        <h4>Categorias Cadastradas</h4>
                    </div>
                    <div class="col-md-4 text-right">
                        <%= link_to new_backoffice_category_path, class: "btn btn-success", title: "Cadastrar Categoria" do %>
                            <i class="fa fa-plus"></i> Novo
                        <% end %>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Descrição</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    	<% @categories.each_with_index do |c,index| %>
                        <tr>
                            <td><%= index %></td>
                            <td><%= c.description %></td>
                            <td>
                                <%= link_to edit_backoffice_category_path(c), class: "btn btn-primary btn-sm", title: "Editar" do %>
                                    <i class="fa fa-edit"></i>
                                <% end %>        
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>